name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "30 18 * * *" # 毎日 03:30 JST
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contrib SVGs
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A profile-3d-contrib
          git commit -m "chore: update 3d contrib graph" || echo "no changes"
          git push
